path_planner_dijkstra_node_yankee:
  ros__parameters:
    occ_thresh: 100
    robot_radius_m: 0.3
    safety_margin_m: 0.05
path_planner_Astar_node_yankee:
  ros__parameters:
    occ_thresh: 100
    robot_radius_m: 0.3
    safety_margin_m: 0.05